# ndarray的创建
## 从已有数组创建
### 使用np.array()由python list进行创建
- numpy默认ndarray的所有元素类型相同

- 如果传入的列表包含不同类型，则自动统一为相同类型，优先级：str>float>int

- np.shape查看数组形状，np.reshape修改形状但不改变原数组，np.resize就地修改原数组  

### np.copy、np.asarray()和np.asanyarray()  
- np.copy()复制一个指定数组
- np.asarray()和np.asanyarray()两者都将传入数组变为ndarray或其子类
- 区别在于asarray()将原数组类型变为ndarray, asanyarray()则保留原数组的数据类型(ndarray的子类)  




In [1]:
import numpy as np

print(issubclass(np.matrix, np.ndarray))

a = np.matrix([[1, 2]])
print(type(np.asarray(a)))
print(np.asarray(a) is a)

print(np.asanyarray(a) is a)


True
<class 'numpy.ndarray'>
False
True



### np.fromstring()



In [2]:
a = np.fromstring('1 2', dtype=int, sep=' ')
b = np.fromstring('1, 2', dtype=int, sep=',')
print(a)
print(b)

[1 2]
[1 2]


## 使用routines函数进行创建
- np.empty(shape, dtype=float, order='C')  
__创建具有形状和数据类型的数组，其中的数据都是未初始化数据__  


- np.empty_like(a, dtype=None, order='K', subok=True)  
__创建一个和a数组同形的数组，subok=True则为a的子集类__



In [3]:
a = np.empty((2,2))
b = np.empty_like(a)
print(a)
print(b)

[[8.90104239e-307 6.23059726e-307]
 [1.78021527e-306 1.00132653e-307]]
[[8.77535059e-312 1.42419938e-306]
 [4.45058486e-308 2.55888926e-307]]


- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)  
__其中，start为起始数，stop为终止数，num为取多少个数据，默认为50，endpoint=True时，stop包含在数组中，False则不包含。retstep=True可显示步长__


- np.ones(shape, dtype=None, order='C')  
__指定shape，创建全是1的数组__  
*np.ones_like则创建与指定数组同形的全为1数组*


- np.zeros(shape, dtype=float, order='C')  
__指定shape，创建全是0的数组__   
*np.zeros_like则创建与指定数组同形的全为0数组*  


- np.full(shape, fill_value, dtype=None, order='C')  
__指定shape，fill_value,创建全是指定值的数组__  
*np.full_like则创建与指定数组同形的全为fill_value的数组*


- np.eye(N, M=None, k=0, dtype=float)  
__其中N位行数，M为列数，缺省为方阵。k为主轴偏移量，见实例__  


In [4]:
# np.eye()中关于参数 k 的实例
a = np.eye(3, k=0)
b = np.eye(3, k=1)
c = np.eye(3, k=-1)
print(a)
print(b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


- np.identity(n, dtype=None)  
__创建主轴为1，其余为0的方阵，与np.eye功能相同，区别在于np.eye可以指定M参数以创建非方阵__


- np.ones

# ```ndarray```数组的索引和切片

## ```ndarray```切片操作的不复制性

numpy的数组切片操作不会复制产生一个新的数组，它的操作只是原始数组的一个“view”

In [5]:
a = np.arange(10)
a
a_slice = a[3:6]
a_slice[:] = 100
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([  0,   1,   2, 100, 100, 100,   6,   7,   8,   9])

## ```ndarray```的布尔索引

### ```ndarray```进行布尔索引时，**可以混合切片操作对数组进行索引。**

In [6]:
a = np.random.randn(7,4)
a
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a[names == 'Bob']

# 布尔索引和切片操作混合使用
a[names == 'Bob',1:]

array([[ 3.05165155e-02,  1.58360304e-01, -6.87980899e-01,
         9.04670760e-05],
       [-1.72344938e+00, -4.15380085e-01, -1.45646135e+00,
        -1.81512569e+00],
       [-1.43468276e+00, -1.08892791e+00, -8.88796918e-02,
        -7.12294119e-01],
       [ 1.70271568e+00,  9.08178689e-01, -1.74421393e+00,
         1.58627904e+00],
       [-7.51653057e-02,  2.55781490e+00,  1.04941596e-01,
         1.74064007e+00],
       [ 1.53047155e+00,  4.20120683e-01, -8.33758181e-03,
        -7.93455945e-01],
       [ 7.45041614e-01,  1.56789401e+00, -9.17400506e-01,
        -4.46112024e-01]])

array([[ 3.05165155e-02,  1.58360304e-01, -6.87980899e-01,
         9.04670760e-05],
       [ 1.70271568e+00,  9.08178689e-01, -1.74421393e+00,
         1.58627904e+00]])

array([[ 1.58360304e-01, -6.87980899e-01,  9.04670760e-05],
       [ 9.08178689e-01, -1.74421393e+00,  1.58627904e+00]])

### 使用`~`操作符来进行反选

In [7]:
a[names == 'Bob']
a[~(names == 'Bob')]

array([[ 3.05165155e-02,  1.58360304e-01, -6.87980899e-01,
         9.04670760e-05],
       [ 1.70271568e+00,  9.08178689e-01, -1.74421393e+00,
         1.58627904e+00]])

array([[-1.72344938, -0.41538009, -1.45646135, -1.81512569],
       [-1.43468276, -1.08892791, -0.08887969, -0.71229412],
       [-0.07516531,  2.5578149 ,  0.1049416 ,  1.74064007],
       [ 1.53047155,  0.42012068, -0.00833758, -0.79345595],
       [ 0.74504161,  1.56789401, -0.91740051, -0.44611202]])

### 使用布尔运算操作符`&`和`|`进行复合索引

In [8]:
cond = (names == 'Bob')|(names == 'Will')
a[~cond]

array([[-1.72344938, -0.41538009, -1.45646135, -1.81512569],
       [ 1.53047155,  0.42012068, -0.00833758, -0.79345595],
       [ 0.74504161,  1.56789401, -0.91740051, -0.44611202]])

### 布尔索引和切片索引在复制性上的区别

与切片索引不同（切片返回的只是原数组的一个‘view’，具有不复制性），**布尔索引总是会复制原数组的目标部分。**

In [9]:
# 对布尔索引返回的数组进行重新赋值，不会影响到原数组
b= a[names == 'Bob']
b[:]=100
b
a

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.]])

array([[ 3.05165155e-02,  1.58360304e-01, -6.87980899e-01,
         9.04670760e-05],
       [-1.72344938e+00, -4.15380085e-01, -1.45646135e+00,
        -1.81512569e+00],
       [-1.43468276e+00, -1.08892791e+00, -8.88796918e-02,
        -7.12294119e-01],
       [ 1.70271568e+00,  9.08178689e-01, -1.74421393e+00,
         1.58627904e+00],
       [-7.51653057e-02,  2.55781490e+00,  1.04941596e-01,
         1.74064007e+00],
       [ 1.53047155e+00,  4.20120683e-01, -8.33758181e-03,
        -7.93455945e-01],
       [ 7.45041614e-01,  1.56789401e+00, -9.17400506e-01,
        -4.46112024e-01]])

In [10]:
# 对切片索引返回的数组重新赋值，原数组也随之改变
b=a[1,1:2]
b
b[0]=100
a

array([-0.41538009])

array([[ 3.05165155e-02,  1.58360304e-01, -6.87980899e-01,
         9.04670760e-05],
       [-1.72344938e+00,  1.00000000e+02, -1.45646135e+00,
        -1.81512569e+00],
       [-1.43468276e+00, -1.08892791e+00, -8.88796918e-02,
        -7.12294119e-01],
       [ 1.70271568e+00,  9.08178689e-01, -1.74421393e+00,
         1.58627904e+00],
       [-7.51653057e-02,  2.55781490e+00,  1.04941596e-01,
         1.74064007e+00],
       [ 1.53047155e+00,  4.20120683e-01, -8.33758181e-03,
        -7.93455945e-01],
       [ 7.45041614e-01,  1.56789401e+00, -9.17400506e-01,
        -4.46112024e-01]])

### 利用布尔索引重新赋值特定值

In [11]:
data = np.random.randn(5,5)
data[data<1]=0
data
data[data==0]=1
data

array([[0.        , 0.        , 0.        , 0.        , 1.08465896],
       [1.43863819, 1.29685954, 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 1.21273017]])

array([[1.        , 1.        , 1.        , 1.        , 1.08465896],
       [1.43863819, 1.29685954, 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.21273017]])

### 花式索引

In [12]:
data=np.empty((5,5))
for i in range(5):
    data[i] = i
data
data[[4,2,0]]
data[[4,2,0],:]
data[[4,2,0],[1]]
# data[[4,2,0],[1,2]] 由于维度不匹配，会引起错误
data[[4,2,0],[1,2,4]]  # 两个数组的值一一对应形成了3个坐标点，返回一个一维数组
data[[4,2,0]][:,[1,2,4]]  # 通过两次花式索引返回一个矩形方框内的数组

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

array([[4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.]])

array([[4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.]])

array([4., 2., 0.])

array([4., 2., 0.])

array([[4., 4., 4.],
       [2., 2., 2.],
       [0., 0., 0.]])

需要注意的是：

- 花式索引和布尔索引一样，会创建原数组的一个复制。
- 切片索引则只是原数组的一个‘view’，其上的操作不会改变原数组。

# ```ndarray```数组的转置和轴变化

## 转置

In [13]:
# 两种方法：ndarray.T属性和ndarray.transpose()方法
a = np.random.randn(5,3)
a.transpose()
a.T

array([[ 0.33551302, -0.92171334,  0.11178461, -0.64838518, -0.89711118],
       [ 0.78074237, -0.87387376, -0.27523246,  0.87504988, -1.36991246],
       [-0.77894808,  0.74963708, -0.60806912, -0.39429991,  1.95728409]])

array([[ 0.33551302, -0.92171334,  0.11178461, -0.64838518, -0.89711118],
       [ 0.78074237, -0.87387376, -0.27523246,  0.87504988, -1.36991246],
       [-0.77894808,  0.74963708, -0.60806912, -0.39429991,  1.95728409]])

## 轴变换

- ndarray.T是最简单的轴变换

- ```ndarray.transpose()```可以接受一个元组，用以表示轴的交换顺序

In [14]:
a = np.random.randn(2,2,4)
a
a.transpose(1,0,2)

array([[[-0.20034546,  0.99043638, -0.19665417,  0.48876718],
        [-0.2539418 ,  0.08517046, -0.59466   , -1.3700174 ]],

       [[-0.80914778,  0.58811715,  0.90798738,  0.71315029],
        [-0.70544647, -0.70782429, -0.20834517, -0.52891082]]])

array([[[-0.20034546,  0.99043638, -0.19665417,  0.48876718],
        [-0.80914778,  0.58811715,  0.90798738,  0.71315029]],

       [[-0.2539418 ,  0.08517046, -0.59466   , -1.3700174 ],
        [-0.70544647, -0.70782429, -0.20834517, -0.52891082]]])

- ```ndarray.swapaxes()```对换两个轴的顺序

In [15]:
a = np.random.randn(2,2,4)
a
a.swapaxes(0,1)

array([[[-0.81140317,  1.79020023,  0.51059763, -1.59090933],
        [ 0.26139785,  1.13631292,  0.39855895,  0.44797898]],

       [[-1.24839548, -0.0988213 ,  0.57810655, -0.54544969],
        [-0.02036017,  0.18559983, -1.88612177, -2.82263358]]])

array([[[-0.81140317,  1.79020023,  0.51059763, -1.59090933],
        [-1.24839548, -0.0988213 ,  0.57810655, -0.54544969]],

       [[ 0.26139785,  1.13631292,  0.39855895,  0.44797898],
        [-0.02036017,  0.18559983, -1.88612177, -2.82263358]]])