# 1 一元通用函数

## 1.1 ```np.abs```和```np.fabs```都能够返回数组的绝对值。
- ```np.abs()```能够返回**复数**的绝对值
- ```np.fabs()```只能够返回**浮点数**和**整数**的绝对值

## 1.2 ```np.sqrt```和```np.square```分别求根和平方

In [1]:
import numpy as np
a = np.array([1,2,3,4,5])
np.sqrt(a)
np.square(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

array([ 1,  4,  9, 16, 25], dtype=int32)

## 1.3 ```np.exp```、```np.log```、```np.log10```、```np.log2```、```np.log1p```等对数函数

* ```np.exp```即求$e^x$的值

In [2]:
a = np.array([1,2,3,4])
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

* ```np.log```即求$lnx$的值

In [3]:
a = np.array([1,2,3,4])
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

* ```np.log10```即求$log_{10}x$的值,```np.log2```同理

In [4]:
a = np.array([10,100,1000,10000])
np.log10(a)

array([1., 2., 3., 4.])

* ```np.log1p```即$ln(1+x)$的值

In [5]:
a
np.log1p(a)

array([   10,   100,  1000, 10000])

array([2.39789527, 4.61512052, 6.90875478, 9.21044037])

## 1.4 ```np.sign```和```np.ceil\np.floor```函数

In [6]:
# np.sign函数用以标记数组中的值正负：1表示正，-1表示负，0表示零
a = np.random.randn(5,5)
np.sign(a)

array([[ 1.,  1.,  1., -1., -1.],
       [-1.,  1.,  1.,  1.,  1.],
       [ 1.,  1., -1.,  1.,  1.],
       [ 1., -1., -1.,  1.,  1.],
       [-1., -1.,  1., -1., -1.]])

In [7]:
# np.ceil函数返回数组中每个值的“ceil value”，即大于当前值的最小值
a*10
np.ceil(a*10)

array([[  6.77017895,   9.80237202,  15.36142335,  -1.42988982,
        -26.80051016],
       [ -2.57161826,   2.33880447,   2.38597427,   8.86874999,
          8.18031281],
       [  8.88435347,  18.85010493, -22.6213526 ,  20.64982933,
          6.34030456],
       [ 24.78846566,  -4.17591627,  -0.87976126,   6.26356673,
          7.47421236],
       [-16.60456245,  -5.16027613,   9.33021374,  -3.85512628,
         -5.57954696]])

array([[  7.,  10.,  16.,  -1., -26.],
       [ -2.,   3.,   3.,   9.,   9.],
       [  9.,  19., -22.,  21.,   7.],
       [ 25.,  -4.,  -0.,   7.,   8.],
       [-16.,  -5.,  10.,  -3.,  -5.]])

In [8]:
# np.floor函数返回数组中每个值的“floor value”，即小于当前值的最大值
a*10
np.floor(a*10)

array([[  6.77017895,   9.80237202,  15.36142335,  -1.42988982,
        -26.80051016],
       [ -2.57161826,   2.33880447,   2.38597427,   8.86874999,
          8.18031281],
       [  8.88435347,  18.85010493, -22.6213526 ,  20.64982933,
          6.34030456],
       [ 24.78846566,  -4.17591627,  -0.87976126,   6.26356673,
          7.47421236],
       [-16.60456245,  -5.16027613,   9.33021374,  -3.85512628,
         -5.57954696]])

array([[  6.,   9.,  15.,  -2., -27.],
       [ -3.,   2.,   2.,   8.,   8.],
       [  8.,  18., -23.,  20.,   6.],
       [ 24.,  -5.,  -1.,   6.,   7.],
       [-17.,  -6.,   9.,  -4.,  -6.]])

## 1.5 ```np.rint```和```np.modf```函数

In [9]:
# np.rint函数返回数组中值的最接近整数，并保持dtype不变
a
np.rint(a)

array([[ 0.6770179 ,  0.9802372 ,  1.53614233, -0.14298898, -2.68005102],
       [-0.25716183,  0.23388045,  0.23859743,  0.886875  ,  0.81803128],
       [ 0.88843535,  1.88501049, -2.26213526,  2.06498293,  0.63403046],
       [ 2.47884657, -0.41759163, -0.08797613,  0.62635667,  0.74742124],
       [-1.66045624, -0.51602761,  0.93302137, -0.38551263, -0.5579547 ]])

array([[ 1.,  1.,  2., -0., -3.],
       [-0.,  0.,  0.,  1.,  1.],
       [ 1.,  2., -2.,  2.,  1.],
       [ 2., -0., -0.,  1.,  1.],
       [-2., -1.,  1., -0., -1.]])

In [10]:
# np.modf函数返回数组中值的整数部分和小数部分，以一个包含两个array数组的元组形式返回
a
np.modf(a)

array([[ 0.6770179 ,  0.9802372 ,  1.53614233, -0.14298898, -2.68005102],
       [-0.25716183,  0.23388045,  0.23859743,  0.886875  ,  0.81803128],
       [ 0.88843535,  1.88501049, -2.26213526,  2.06498293,  0.63403046],
       [ 2.47884657, -0.41759163, -0.08797613,  0.62635667,  0.74742124],
       [-1.66045624, -0.51602761,  0.93302137, -0.38551263, -0.5579547 ]])

(array([[ 0.6770179 ,  0.9802372 ,  0.53614233, -0.14298898, -0.68005102],
        [-0.25716183,  0.23388045,  0.23859743,  0.886875  ,  0.81803128],
        [ 0.88843535,  0.88501049, -0.26213526,  0.06498293,  0.63403046],
        [ 0.47884657, -0.41759163, -0.08797613,  0.62635667,  0.74742124],
        [-0.66045624, -0.51602761,  0.93302137, -0.38551263, -0.5579547 ]]),
 array([[ 0.,  0.,  1., -0., -2.],
        [-0.,  0.,  0.,  0.,  0.],
        [ 0.,  1., -2.,  2.,  0.],
        [ 2., -0., -0.,  0.,  0.],
        [-1., -0.,  0., -0., -0.]]))

## 1.6 ```np.isnan```和```np.isfinite\np.isinf```函数

In [11]:
# np.isnan函数判断数组中值是否为NaN
a = np.random.randn(3,5)
a[1,1] = np.nan
np.isnan(a)

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [12]:
# np.isfinite函数判断数组中值是否为有限的（非无限或NaN）
a = np.random.randn(3,5)
a[1,1] = np.nan
np.isfinite(a)

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [13]:
# np.isinf函数判断数组中值是否为无限大，同时可以指定out参数以就地将返回结果赋值
y=np.array([1,1,1])
np.isinf(np.array([np.inf,-np.inf,np.nan]),y)
y

array([1, 1, 0])

array([1, 1, 0])

## 1.7 一系列三角函数
> sin,cos,tan

> sinh,cosh,tanh

>arcsin,arccos,arctan

>arcsinh,arccosh,arctanh

## 1.8 ```np.logical_not\np.logical_and\np.logical_or\np.logical_xor```函数

In [14]:
# XOR为异或运算，表示两个值相同时返回0，两个值不同时返回1
a = np.arange(5)
np.logical_and(a>2, a<4)
np.logical_not(a<3)
np.logical_or(a>3, a<1)
np.logical_xor(a>3, a<1)

array([False, False, False,  True, False])

array([False, False, False,  True,  True])

array([ True, False, False, False,  True])

array([ True, False, False, False,  True])

# 2 二元通用函数

## 2.1 ```np.add\np.subtract\np.multiply\np.divide\np.floor_divide```加减乘除及整除运算

In [15]:
a = np.zeros((5,5))
b = np.random.randn(5,5)
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)

array([[ 0.50130431, -1.54581474,  1.31943337,  1.5204367 ,  0.2795955 ],
       [ 0.21134351, -0.19400501,  0.91712403,  0.29428362,  0.26162154],
       [-1.63380347,  0.3820166 , -0.95903849,  1.46898097, -1.10425618],
       [-0.58847182,  0.65203337, -1.29518984, -1.0467641 ,  0.39757557],
       [ 1.00227447, -1.45738517,  0.37080432,  0.01322235, -2.08997768]])

array([[-0.50130431,  1.54581474, -1.31943337, -1.5204367 , -0.2795955 ],
       [-0.21134351,  0.19400501, -0.91712403, -0.29428362, -0.26162154],
       [ 1.63380347, -0.3820166 ,  0.95903849, -1.46898097,  1.10425618],
       [ 0.58847182, -0.65203337,  1.29518984,  1.0467641 , -0.39757557],
       [-1.00227447,  1.45738517, -0.37080432, -0.01322235,  2.08997768]])

array([[ 0., -0.,  0.,  0.,  0.],
       [ 0., -0.,  0.,  0.,  0.],
       [-0.,  0., -0.,  0., -0.],
       [-0.,  0., -0., -0.,  0.],
       [ 0., -0.,  0.,  0., -0.]])

In [16]:
# np.floor_divide运算返回除法运算的整数部分
a = np.array([1,2,3,4])
b = np.array([2,2,2,2])
np.divide(a,b)
np.floor_divide(a,b)

array([0.5, 1. , 1.5, 2. ])

array([0, 1, 1, 2], dtype=int32)

## 2.2 ```np.power```乘方运算

In [17]:
a = np.arange(9).reshape(3,3)
np.power(a,[1,2,3])

array([[  0,   1,   8],
       [  3,  16, 125],
       [  6,  49, 512]], dtype=int32)

## 2.3 ```np.maximum\np.fmax```函数(```np.minimun\np.fmin```同理)

In [18]:
# np.maximum函数返回数组中的最大值
a = np.arange(9).reshape(3,3)
b = a+1
np.maximum(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
# np.fmax返回数组中的最大值并且忽略NaN
a = np.array([[0,1,2],[np.nan,4,5],[6,7,8]])
a
b = np.arange(1,10).reshape(3,3)
# np.maximum(a,b)
np.fmax(a,b)

array([[ 0.,  1.,  2.],
       [nan,  4.,  5.],
       [ 6.,  7.,  8.]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## 2.4 ```np.mod```求余函数

In [20]:
np.mod([1,2,3],2)

array([1, 0, 1], dtype=int32)

## 2.5 ```np.copysign```复制正负函数

In [21]:
np.copysign([1,2,3],-2)
np.copysign([1,2,3],[1,-2,-3])

array([-1., -2., -3.])

array([ 1., -2., -3.])

## 2.6 一系列比较运算符 $>,\ge,<,\le,==,!=$

In [22]:
# 大于
np.greater
# 大于等于
np.greater_equal
# 小于
np.less
# 小于等于
np.less_equal
# 等于
np.equal
# 不等于
np.not_equal

<ufunc 'greater'>

<ufunc 'greater_equal'>

<ufunc 'less'>

<ufunc 'less_equal'>

<ufunc 'equal'>

<ufunc 'not_equal'>