- ```np.diag()```：提取数组的对角线（可以通过参数k设置偏移对角线）元素，也可将一维数组变为相应的方阵。也可作为方法使用。

In [34]:
import numpy as np
from numpy.linalg import inv,qr,det,eig,svd,solve,lstsq
x = np.random.randn(4,4)
x
np.diag(x)
x.diagonal()
np.diag(np.diag(x))

array([[ 0.82772744, -0.94389153,  0.31430266,  1.32507071],
       [-0.96313735,  0.19410952, -0.70040036, -0.51109536],
       [ 0.16790609,  0.276906  ,  0.32443793,  1.71006789],
       [ 0.52573188,  0.99512444, -0.18908326, -0.3194369 ]])

array([ 0.82772744,  0.19410952,  0.32443793, -0.3194369 ])

array([ 0.82772744,  0.19410952,  0.32443793, -0.3194369 ])

array([[ 0.82772744,  0.        ,  0.        ,  0.        ],
       [ 0.        ,  0.19410952,  0.        ,  0.        ],
       [ 0.        ,  0.        ,  0.32443793,  0.        ],
       [ 0.        ,  0.        ,  0.        , -0.3194369 ]])

- ```np.dot()```：矩阵的乘法运算。也可以作为方法运用。

    另外，还可以使用$@$符号代替。

In [8]:
x.dot(x.T)
np.dot(x,x.T)
x@x.T

array([[ 4.46512575, -0.28703836, -0.88820773,  0.87982034],
       [-0.28703836,  7.52096216,  2.74756973,  0.98120933],
       [-0.88820773,  2.74756973,  5.32106906, -0.96571192],
       [ 0.87982034,  0.98120933, -0.96571192,  0.6710886 ]])

array([[ 4.46512575, -0.28703836, -0.88820773,  0.87982034],
       [-0.28703836,  7.52096216,  2.74756973,  0.98120933],
       [-0.88820773,  2.74756973,  5.32106906, -0.96571192],
       [ 0.87982034,  0.98120933, -0.96571192,  0.6710886 ]])

array([[ 4.46512575, -0.28703836, -0.88820773,  0.87982034],
       [-0.28703836,  7.52096216,  2.74756973,  0.98120933],
       [-0.88820773,  2.74756973,  5.32106906, -0.96571192],
       [ 0.87982034,  0.98120933, -0.96571192,  0.6710886 ]])

- ```np.trace()```：计算主对角元素的和。也可作为方法使用。

In [7]:
x = np.random.randn(4,4)
x
np.trace(x)
x.trace()

array([[-1.31651245,  1.24655329, -0.94878771, -0.52709346],
       [ 2.22258153,  1.12242305, -0.93653895, -0.66644939],
       [ 1.08419339, -0.09695685, -1.4740584 ,  1.40119412],
       [ 0.01330356,  0.37375146, -0.05079741, -0.72707708]])

-2.39522488508046

-2.39522488508046

- ```np.linalg.det()```：计算所给矩阵的行列式值

In [16]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
y = np.array([[1,7,2],[3,2,1],[4,3,2]])
det(x)
det(y)

0.0

-11.000000000000002

- ```np.linalg.eig()```：计算所给矩阵的特征值和特征向量。

In [19]:
x = [[1,2,3],[2,4,6],[5,3,9]]
eig(x)

(array([ 1.30827625e+01, -8.35688847e-16,  9.17237470e-01]),
 array([[-0.28560932, -0.69853547, -0.38202165],
        [-0.57121864, -0.46569032, -0.7640433 ],
        [-0.76950411,  0.54330537,  0.51990123]]))

- ```np.linalg.inv()```：计算逆矩阵。

In [25]:
x = np.random.randn(3,3)
inv(x)
x.dot(inv(x))

array([[-0.20293022,  1.25389884, -0.14518972],
       [-0.83132752, -0.49523599,  0.68764279],
       [-0.13959647, -0.23612156,  0.90204968]])

array([[ 1.00000000e+00,  4.44633767e-17, -2.07345653e-17],
       [-1.52738601e-17,  1.00000000e+00,  1.16992610e-17],
       [-1.08732632e-17, -1.88721121e-17,  1.00000000e+00]])

- ```np.linalg.qr()```：QR分解。

In [26]:
qr(x)

(array([[-0.39259493, -0.90771541, -0.14806064],
        [ 0.90279966, -0.34961895, -0.25043836],
        [ 0.17556195, -0.23198993,  0.95674379]]),
 array([[ 0.84302885,  0.24197161,  0.14585787],
        [ 0.        ,  1.30169945, -1.24948126],
        [ 0.        ,  0.        ,  1.06063314]]))

- ```np.linalg.svd()```：奇异值分解。

In [29]:
# 中间的矩阵为奇异值矩阵，因为除了对角线的值都为0，且从大到小排列，因此省略的表示为一维矩阵。
x = [[1,1],[1,-2],[2,1]]
svd()

(array([[-5.34522484e-01, -9.06988786e-17, -8.45154255e-01],
        [ 2.67261242e-01, -9.48683298e-01, -1.69030851e-01],
        [-8.01783726e-01, -3.16227766e-01,  5.07092553e-01]]),
 array([2.64575131, 2.23606798]),
 array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]))

- ```np.linalg.solve()```：计算非齐次方程组$Ax=b$的$x$值，其中A为方阵。

In [33]:
A = [[1,2,3],[1,4,3],[3,5,7]]
solve(A,[1,1,1])

array([-2.00000000e+00, -4.75809868e-17,  1.00000000e+00])

- ```np.linarg.lstsq()```：计算非齐次方程组$Ax=b$的最小二乘解。

In [36]:
A = [[1,2,3],[1,4,3],[3,5,7]]
lstsq(A,[1,1,1],rcond=None)

(array([-2.0000000e+00,  4.4408921e-16,  1.0000000e+00]),
 array([], dtype=float64),
 3,
 array([10.99009678,  1.46844817,  0.24785624]))