# ndarray的创建
## 从已有数组创建
### 使用np.array()由python list进行创建
- numpy默认ndarray的所有元素类型相同

- 如果传入的列表包含不同类型，则自动统一为相同类型，优先级：str>float>int

- np.shape查看数组形状，np.reshape修改形状但不改变原数组，np.resize就地修改原数组  

### np.copy、np.asarray()和np.asanyarray()  
- np.copy()复制一个指定数组
- np.asarray()和np.asanyarray()两者都将传入数组变为ndarray或其子类
- 区别在于asarray()将原数组类型变为ndarray, asanyarray()则保留原数组的数据类型(ndarray的子类)  




In [51]:
import numpy as np

print(issubclass(np.matrix, np.ndarray))

a = np.matrix([[1, 2]])
print(type(np.asarray(a)))
print(np.asarray(a) is a)

print(np.asanyarray(a) is a)


True
<class 'numpy.ndarray'>
False
True



### np.fromstring()



In [52]:
a = np.fromstring('1 2', dtype=int, sep=' ')
b = np.fromstring('1, 2', dtype=int, sep=',')
print(a)
print(b)

[1 2]
[1 2]


## 使用routines函数进行创建
- np.empty(shape, dtype=float, order='C')  
__创建具有形状和数据类型的数组，其中的数据都是未初始化数据__  


- np.empty_like(a, dtype=None, order='K', subok=True)  
__创建一个和a数组同形的数组，subok=True则为a的子集类__



In [53]:
a = np.empty((2,2))
b = np.empty_like(a)
print(a)
print(b)

[[0.0e+000 9.9e-324]
 [1.5e-323 2.0e-323]]
[[0.0e+000 9.9e-324]
 [1.5e-323 2.0e-323]]


- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)  
__其中，start为起始数，stop为终止数，num为取多少个数据，默认为50，endpoint=True时，stop包含在数组中，False则不包含。retstep=True可显示步长__


- np.ones(shape, dtype=None, order='C')  
__指定shape，创建全是1的数组__  
*np.ones_like则创建与指定数组同形的全为1数组*


- np.zeros(shape, dtype=float, order='C')  
__指定shape，创建全是0的数组__   
*np.zeros_like则创建与指定数组同形的全为0数组*  


- np.full(shape, fill_value, dtype=None, order='C')  
__指定shape，fill_value,创建全是指定值的数组__  
*np.full_like则创建与指定数组同形的全为fill_value的数组*


- np.eye(N, M=None, k=0, dtype=float)  
__其中N位行数，M为列数，缺省为方阵。k为主轴偏移量，见实例__  


In [54]:
# np.eye()中关于参数 k 的实例
a = np.eye(3, k=0)
b = np.eye(3, k=1)
c = np.eye(3, k=-1)
print(a)
print(b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


- np.identity(n, dtype=None)  
__创建主轴为1，其余为0的方阵，与np.eye功能相同，区别在于np.eye可以指定M参数以创建非方阵__


- np.ones

# ```ndarray```数组的索引和切片

## ```ndarray```切片操作的不复制性

numpy的数组切片操作不会复制产生一个新的数组，它的操作只是原始数组的一个“view”

In [55]:
a = np.arange(10)
a
a_slice = a[3:6]
a_slice[:] = 100
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([  0,   1,   2, 100, 100, 100,   6,   7,   8,   9])

## ```ndarray```的布尔索引

### ```ndarray```进行布尔索引时，**可以混合切片操作对数组进行索引。**

In [56]:
a = np.random.randn(7,4)
a
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a[names == 'Bob']

# 布尔索引和切片操作混合使用
a[names == 'Bob',1:]

array([[ 0.3281357 ,  0.77819138, -1.06037078,  0.6710272 ],
       [ 1.03107881, -0.64941308,  0.99174844, -0.09666809],
       [ 1.08956805, -1.85883489,  0.75539183,  1.03702654],
       [ 0.93663118,  0.31664813, -0.22306418, -1.16719356],
       [ 1.1681664 ,  0.40892485,  0.65609603,  0.72212127],
       [ 0.50004679, -0.00891231, -0.67754652, -0.46754675],
       [-0.16990487, -1.44915673,  0.43844795,  1.24728752]])

array([[ 0.3281357 ,  0.77819138, -1.06037078,  0.6710272 ],
       [ 0.93663118,  0.31664813, -0.22306418, -1.16719356]])

array([[ 0.77819138, -1.06037078,  0.6710272 ],
       [ 0.31664813, -0.22306418, -1.16719356]])

### 使用`~`操作符来进行反选

In [57]:
a[names == 'Bob']
a[~(names == 'Bob')]

array([[ 0.3281357 ,  0.77819138, -1.06037078,  0.6710272 ],
       [ 0.93663118,  0.31664813, -0.22306418, -1.16719356]])

array([[ 1.03107881, -0.64941308,  0.99174844, -0.09666809],
       [ 1.08956805, -1.85883489,  0.75539183,  1.03702654],
       [ 1.1681664 ,  0.40892485,  0.65609603,  0.72212127],
       [ 0.50004679, -0.00891231, -0.67754652, -0.46754675],
       [-0.16990487, -1.44915673,  0.43844795,  1.24728752]])

### 使用布尔运算操作符`&`和`|`进行复合索引

In [58]:
cond = (names == 'Bob')|(names == 'Will')
a[~cond]

array([[ 1.03107881, -0.64941308,  0.99174844, -0.09666809],
       [ 0.50004679, -0.00891231, -0.67754652, -0.46754675],
       [-0.16990487, -1.44915673,  0.43844795,  1.24728752]])

### 布尔索引和切片索引在复制性上的区别

与切片索引不同（切片返回的只是原数组的一个‘view’，具有不复制性），**布尔索引总是会复制原数组的目标部分。**

In [70]:
# 对布尔索引返回的数组进行重新赋值，不会影响到原数组
b= a[names == 'Bob']
b[:]=100
b
a

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.]])

array([[ 0.3281357 ,  0.77819138, -1.06037078,  0.6710272 ],
       [ 1.03107881, -0.64941308,  0.99174844, -0.09666809],
       [ 1.08956805, -1.85883489,  0.75539183,  1.03702654],
       [ 0.93663118,  0.31664813, -0.22306418, -1.16719356],
       [ 1.1681664 ,  0.40892485,  0.65609603,  0.72212127],
       [ 0.50004679, -0.00891231, -0.67754652, -0.46754675],
       [-0.16990487, -1.44915673,  0.43844795,  1.24728752]])

In [78]:
# 对切片索引返回的数组重新赋值，原数组也随之改变
b=a[1,1:2]
b
b[0]=100
a

array([100.])

array([[ 3.28135700e-01,  7.78191380e-01, -1.06037078e+00,
         6.71027201e-01],
       [ 1.03107881e+00,  1.00000000e+02,  9.91748443e-01,
        -9.66680887e-02],
       [ 1.08956805e+00, -1.85883489e+00,  7.55391834e-01,
         1.03702654e+00],
       [ 9.36631185e-01,  3.16648128e-01, -2.23064183e-01,
        -1.16719356e+00],
       [ 1.16816640e+00,  4.08924849e-01,  6.56096034e-01,
         7.22121270e-01],
       [ 5.00046795e-01, -8.91230817e-03, -6.77546523e-01,
        -4.67546751e-01],
       [-1.69904874e-01, -1.44915673e+00,  4.38447955e-01,
         1.24728752e+00]])

### 利用布尔索引重新赋值特定值

In [89]:
data = np.random.randn(5,5)
data[data<1]=0
data
data[data==0]=1
data

array([[0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 1.2015319 , 0.        , 1.39764022, 1.38085077],
       [0.        , 1.32871652, 0.        , 3.20534882, 1.10886823],
       [0.        , 0.        , 0.        , 0.        , 1.1905394 ]])

array([[1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.2015319 , 1.        , 1.39764022, 1.38085077],
       [1.        , 1.32871652, 1.        , 3.20534882, 1.10886823],
       [1.        , 1.        , 1.        , 1.        , 1.1905394 ]])

### 花式索引

In [106]:
data=np.empty((5,5))
for i in range(5):
    data[i] = i
data
data[[4,2,0]]
data[[4,2,0],:]
data[[4,2,0],[1]]
# data[[4,2,0],[1,2]] 由于维度不匹配，会引起错误
data[[4,2,0],[1,2,4]]  # 两个数组的值一一对应形成了3个坐标点，返回一个一维数组
data[[4,2,0]][:,[1,2,4]]  # 通过两次花式索引返回一个矩形方框内的数组

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

array([[4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.]])

array([[4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.]])

array([4., 2., 0.])

array([4., 2., 0.])

array([[4., 4., 4.],
       [2., 2., 2.],
       [0., 0., 0.]])

需要注意的是：

- 花式索引和布尔索引一样，会创建原数组的一个复制。
- 切片索引则只是原数组的一个‘view’，其上的操作不会改变原数组。