# ndarray的创建
## 从已有数组创建
### 使用np.array()由python list进行创建
- numpy默认ndarray的所有元素类型相同

- 如果传入的列表包含不同类型，则自动统一为相同类型，优先级：str>float>int

- np.shape查看数组形状，np.reshape修改形状但不改变原数组，np.resize就地修改原数组  

### np.copy、np.asarray()和np.asanyarray()  
- np.copy()复制一个指定数组
- np.asarray()和np.asanyarray()两者都将传入数组变为ndarray或其子类
- 区别在于asarray()将原数组类型变为ndarray, asanyarray()则保留原数组的数据类型(ndarray的子类)  




In [1]:
import numpy as np

print(issubclass(np.matrix, np.ndarray))

a = np.matrix([[1, 2]])
print(type(np.asarray(a)))
print(np.asarray(a) is a)

print(np.asanyarray(a) is a)


True
<class 'numpy.ndarray'>
False
True



### np.fromstring()



In [2]:
a = np.fromstring('1 2', dtype=int, sep=' ')
b = np.fromstring('1, 2', dtype=int, sep=',')
print(a)
print(b)

[1 2]
[1 2]


## 使用routines函数进行创建
- np.empty(shape, dtype=float, order='C')  
__创建具有形状和数据类型的数组，其中的数据都是未初始化数据__  


- np.empty_like(a, dtype=None, order='K', subok=True)  
__创建一个和a数组同形的数组，subok=True则为a的子集类__



In [3]:
a = np.empty((2,2))
b = np.empty_like(a)
print(a)
print(b)

[[1.04263642e-311 8.01304531e+262]
 [2.60799828e-310 6.01346930e-154]]
[[2.42767960e-154 2.93573416e+222]
 [3.75828563e+199 4.35529477e-114]]


- np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)  
__其中，start为起始数，stop为终止数，num为取多少个数据，默认为50，endpoint=True时，stop包含在数组中，False则不包含。retstep=True可显示步长__


- np.ones(shape, dtype=None, order='C')  
__指定shape，创建全是1的数组__  
*np.ones_like则创建与指定数组同形的全为1数组*


- np.zeros(shape, dtype=float, order='C')  
__指定shape，创建全是0的数组__   
*np.zeros_like则创建与指定数组同形的全为0数组*  


- np.full(shape, fill_value, dtype=None, order='C')  
__指定shape，fill_value,创建全是指定值的数组__  
*np.full_like则创建与指定数组同形的全为fill_value的数组*


- np.eye(N, M=None, k=0, dtype=float)  
__其中N位行数，M为列数，缺省为方阵。k为主轴偏移量，见实例__  


In [4]:
# np.eye()中关于参数 k 的实例
a = np.eye(3, k=0)
b = np.eye(3, k=1)
c = np.eye(3, k=-1)
print(a)
print(b)
print(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]
[[0. 0. 0.]
 [1. 0. 0.]
 [0. 1. 0.]]


- np.identity(n, dtype=None)  
__创建主轴为1，其余为0的方阵，与np.eye功能相同，区别在于np.eye可以指定M参数以创建非方阵__


- np.ones

# ```ndarray```数组的索引和切片

## ```ndarray```切片操作的不复制性

numpy的数组切片操作不会复制产生一个新的数组，它的操作只是原始数组的一个“view”

In [5]:
a = np.arange(10)
a
a_slice = a[3:6]
a_slice[:] = 100
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

array([  0,   1,   2, 100, 100, 100,   6,   7,   8,   9])

## ```ndarray```的布尔索引

### ```ndarray```进行布尔索引时，**可以混合切片操作对数组进行索引。**

In [6]:
a = np.random.randn(7,4)
a
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
a[names == 'Bob']

# 布尔索引和切片操作混合使用
a[names == 'Bob',1:]

array([[ 0.25974555, -1.46891715,  0.10087989,  1.266699  ],
       [ 0.42621529, -0.31242722,  1.30973073, -0.03510822],
       [ 0.19245114, -1.13855551,  1.00681599, -0.18421269],
       [ 2.75520291,  0.11515391,  0.16779128, -1.29938006],
       [-0.39724944,  0.31291604, -0.15899605,  1.5813231 ],
       [ 0.88884494, -0.39555301,  1.07847094,  0.27641004],
       [-0.57077644,  0.59299891, -1.39846765,  0.14027363]])

array([[ 0.25974555, -1.46891715,  0.10087989,  1.266699  ],
       [ 2.75520291,  0.11515391,  0.16779128, -1.29938006]])

array([[-1.46891715,  0.10087989,  1.266699  ],
       [ 0.11515391,  0.16779128, -1.29938006]])

### 使用`~`操作符来进行反选

In [7]:
a[names == 'Bob']
a[~(names == 'Bob')]

array([[ 0.25974555, -1.46891715,  0.10087989,  1.266699  ],
       [ 2.75520291,  0.11515391,  0.16779128, -1.29938006]])

array([[ 0.42621529, -0.31242722,  1.30973073, -0.03510822],
       [ 0.19245114, -1.13855551,  1.00681599, -0.18421269],
       [-0.39724944,  0.31291604, -0.15899605,  1.5813231 ],
       [ 0.88884494, -0.39555301,  1.07847094,  0.27641004],
       [-0.57077644,  0.59299891, -1.39846765,  0.14027363]])

### 使用布尔运算操作符`&`和`|`进行复合索引

In [8]:
cond = (names == 'Bob')|(names == 'Will')
a[~cond]

array([[ 0.42621529, -0.31242722,  1.30973073, -0.03510822],
       [ 0.88884494, -0.39555301,  1.07847094,  0.27641004],
       [-0.57077644,  0.59299891, -1.39846765,  0.14027363]])

### 布尔索引和切片索引在复制性上的区别

与切片索引不同（切片返回的只是原数组的一个‘view’，具有不复制性），**布尔索引总是会复制原数组的目标部分。**

In [9]:
# 对布尔索引返回的数组进行重新赋值，不会影响到原数组
b= a[names == 'Bob']
b[:]=100
b
a

array([[100., 100., 100., 100.],
       [100., 100., 100., 100.]])

array([[ 0.25974555, -1.46891715,  0.10087989,  1.266699  ],
       [ 0.42621529, -0.31242722,  1.30973073, -0.03510822],
       [ 0.19245114, -1.13855551,  1.00681599, -0.18421269],
       [ 2.75520291,  0.11515391,  0.16779128, -1.29938006],
       [-0.39724944,  0.31291604, -0.15899605,  1.5813231 ],
       [ 0.88884494, -0.39555301,  1.07847094,  0.27641004],
       [-0.57077644,  0.59299891, -1.39846765,  0.14027363]])

In [10]:
# 对切片索引返回的数组重新赋值，原数组也随之改变
b=a[1,1:2]
b
b[0]=100
a

array([-0.31242722])

array([[ 2.59745546e-01, -1.46891715e+00,  1.00879891e-01,
         1.26669900e+00],
       [ 4.26215287e-01,  1.00000000e+02,  1.30973073e+00,
        -3.51082190e-02],
       [ 1.92451138e-01, -1.13855551e+00,  1.00681599e+00,
        -1.84212689e-01],
       [ 2.75520291e+00,  1.15153908e-01,  1.67791285e-01,
        -1.29938006e+00],
       [-3.97249444e-01,  3.12916038e-01, -1.58996046e-01,
         1.58132310e+00],
       [ 8.88844944e-01, -3.95553014e-01,  1.07847094e+00,
         2.76410036e-01],
       [-5.70776442e-01,  5.92998909e-01, -1.39846765e+00,
         1.40273633e-01]])

### 利用布尔索引重新赋值特定值

In [11]:
data = np.random.randn(5,5)
data[data<1]=0
data
data[data==0]=1
data

array([[0.        , 1.10525845, 1.29904017, 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.8586813 , 1.57752425],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.        , 0.        ],
       [0.        , 0.        , 0.        , 1.37898442, 1.96799001]])

array([[1.        , 1.10525845, 1.29904017, 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.8586813 , 1.57752425],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.37898442, 1.96799001]])

### 花式索引

In [12]:
data=np.empty((5,5))
for i in range(5):
    data[i] = i
data
data[[4,2,0]]
data[[4,2,0],:]
data[[4,2,0],[1]]
# data[[4,2,0],[1,2]] 由于维度不匹配，会引起错误
data[[4,2,0],[1,2,4]]  # 两个数组的值一一对应形成了3个坐标点，返回一个一维数组
data[[4,2,0]][:,[1,2,4]]  # 通过两次花式索引返回一个矩形方框内的数组

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

array([[4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.]])

array([[4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2.],
       [0., 0., 0., 0., 0.]])

array([4., 2., 0.])

array([4., 2., 0.])

array([[4., 4., 4.],
       [2., 2., 2.],
       [0., 0., 0.]])

需要注意的是：

- 花式索引和布尔索引一样，会创建原数组的一个复制。
- 切片索引则只是原数组的一个‘view’，其上的操作不会改变原数组。

# ```ndarray```数组的转置和轴变化

## 转置

In [13]:
# 两种方法：ndarray.T属性和ndarray.transpose()方法
a = np.random.randn(5,3)
a.transpose()
a.T

array([[ 0.1949061 ,  1.78971635,  0.32188454,  0.44688522, -0.43329778],
       [ 1.22242887,  2.00838707,  1.46612238, -1.59715644,  0.4635925 ],
       [-0.80214327,  0.69476068,  0.3697347 ,  1.50927066,  0.31144172]])

array([[ 0.1949061 ,  1.78971635,  0.32188454,  0.44688522, -0.43329778],
       [ 1.22242887,  2.00838707,  1.46612238, -1.59715644,  0.4635925 ],
       [-0.80214327,  0.69476068,  0.3697347 ,  1.50927066,  0.31144172]])

## 轴变换

- ndarray.T是最简单的轴变换

- ```ndarray.transpose()```可以接受一个元组，用以表示轴的交换顺序

In [14]:
a = np.random.randn(2,2,4)
a
a.transpose(1,0,2)

array([[[ 0.19358055,  1.45961083, -1.04199384,  0.61713007],
        [ 0.73146892, -1.46188063, -0.82009218, -0.79092384]],

       [[ 1.27355801, -0.23046413,  1.98428268, -0.24527132],
        [-0.41622308,  0.2263189 ,  0.35440099, -1.76829713]]])

array([[[ 0.19358055,  1.45961083, -1.04199384,  0.61713007],
        [ 1.27355801, -0.23046413,  1.98428268, -0.24527132]],

       [[ 0.73146892, -1.46188063, -0.82009218, -0.79092384],
        [-0.41622308,  0.2263189 ,  0.35440099, -1.76829713]]])

- ```ndarray.swapaxes()```对换两个轴的顺序

In [15]:
a = np.random.randn(2,2,4)
a
a.swapaxes(0,1)

array([[[-0.59906056,  1.33007815, -0.12047318,  0.17069945],
        [-0.81354483, -1.2345225 ,  0.91538178,  0.70577581]],

       [[ 2.54528152, -0.3670662 ,  0.50643866,  0.39261617],
        [ 0.01565825,  0.6449081 ,  0.32477006, -0.46558493]]])

array([[[-0.59906056,  1.33007815, -0.12047318,  0.17069945],
        [ 2.54528152, -0.3670662 ,  0.50643866,  0.39261617]],

       [[-0.81354483, -1.2345225 ,  0.91538178,  0.70577581],
        [ 0.01565825,  0.6449081 ,  0.32477006, -0.46558493]]])