# 1 一元通用函数

## 1.1 ```np.abs```和```np.fabs```都能够返回数组的绝对值。
- ```np.abs()```能够返回**复数**的绝对值
- ```np.fabs()```只能够返回**浮点数**和**整数**的绝对值

## 1.2 ```np.sqrt```和```np.square```分别求根和平方

In [19]:
a = np.array([1,2,3,4,5])
np.sqrt(a)
np.square(a)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

array([ 1,  4,  9, 16, 25], dtype=int32)

## 1.3 ```np.exp```、```np.log```、```np.log10```、```np.log2```、```np.log1p```等对数函数

* ```np.exp```即求$e^x$的值

In [3]:
a = np.array([1,2,3,4])
np.exp(a)

array([ 2.71828183,  7.3890561 , 20.08553692, 54.59815003])

* ```np.log```即求$lnx$的值

In [2]:
a = np.array([1,2,3,4])
np.log(a)

array([0.        , 0.69314718, 1.09861229, 1.38629436])

* ```np.log10```即求$log_{10}x$的值,```np.log2```同理

In [5]:
a = np.array([10,100,1000,10000])
np.log10(a)

array([1., 2., 3., 4.])

* ```np.log1p```即$ln(1+x)$的值

In [7]:
a
np.log1p(a)

array([   10,   100,  1000, 10000])

array([2.39789527, 4.61512052, 6.90875478, 9.21044037])

## 1.4 ```np.sign```和```np.ceil\np.floor```函数

In [9]:
# np.sign函数用以标记数组中的值正负：1表示正，-1表示负，0表示零
a = np.random.randn(5,5)
np.sign(a)

array([[ 1.,  1., -1.,  1., -1.],
       [-1., -1.,  1., -1.,  1.],
       [ 1., -1., -1., -1., -1.],
       [ 1., -1.,  1., -1.,  1.],
       [ 1.,  1., -1., -1., -1.]])

In [12]:
# np.ceil函数返回数组中每个值的“ceil value”，即大于当前值的最小值
a*10
np.ceil(a*10)

array([[  1.31354077,  14.54641875,  -4.44489551,   2.34422805,
         -4.97131741],
       [ -0.36714813, -12.02330032,   0.51947347, -19.14328079,
          2.73529789],
       [ 11.01456226, -22.91808392,  -4.50144306,  -4.36061473,
         -7.5474979 ],
       [  2.26103602,  -3.54015623,   2.81844538, -18.18179376,
          1.60521052],
       [  8.39208871,   7.43038279, -13.21049845,  -3.34854022,
        -11.75257947]])

array([[  2.,  15.,  -4.,   3.,  -4.],
       [ -0., -12.,   1., -19.,   3.],
       [ 12., -22.,  -4.,  -4.,  -7.],
       [  3.,  -3.,   3., -18.,   2.],
       [  9.,   8., -13.,  -3., -11.]])

In [13]:
# np.floor函数返回数组中每个值的“floor value”，即小于当前值的最大值
a*10
np.floor(a*10)

array([[  1.31354077,  14.54641875,  -4.44489551,   2.34422805,
         -4.97131741],
       [ -0.36714813, -12.02330032,   0.51947347, -19.14328079,
          2.73529789],
       [ 11.01456226, -22.91808392,  -4.50144306,  -4.36061473,
         -7.5474979 ],
       [  2.26103602,  -3.54015623,   2.81844538, -18.18179376,
          1.60521052],
       [  8.39208871,   7.43038279, -13.21049845,  -3.34854022,
        -11.75257947]])

array([[  1.,  14.,  -5.,   2.,  -5.],
       [ -1., -13.,   0., -20.,   2.],
       [ 11., -23.,  -5.,  -5.,  -8.],
       [  2.,  -4.,   2., -19.,   1.],
       [  8.,   7., -14.,  -4., -12.]])

## 1.5 ```np.rint```和```np.modf```函数

In [14]:
# np.rint函数返回数组中值的最接近整数，并保持dtype不变
a
np.rint(a)

array([[ 0.13135408,  1.45464187, -0.44448955,  0.2344228 , -0.49713174],
       [-0.03671481, -1.20233003,  0.05194735, -1.91432808,  0.27352979],
       [ 1.10145623, -2.29180839, -0.45014431, -0.43606147, -0.75474979],
       [ 0.2261036 , -0.35401562,  0.28184454, -1.81817938,  0.16052105],
       [ 0.83920887,  0.74303828, -1.32104985, -0.33485402, -1.17525795]])

array([[ 0.,  1., -0.,  0., -0.],
       [-0., -1.,  0., -2.,  0.],
       [ 1., -2., -0., -0., -1.],
       [ 0., -0.,  0., -2.,  0.],
       [ 1.,  1., -1., -0., -1.]])

In [15]:
# np.modf函数返回数组中值的整数部分和小数部分，以一个包含两个array数组的元组形式返回
a
np.modf(a)

array([[ 0.13135408,  1.45464187, -0.44448955,  0.2344228 , -0.49713174],
       [-0.03671481, -1.20233003,  0.05194735, -1.91432808,  0.27352979],
       [ 1.10145623, -2.29180839, -0.45014431, -0.43606147, -0.75474979],
       [ 0.2261036 , -0.35401562,  0.28184454, -1.81817938,  0.16052105],
       [ 0.83920887,  0.74303828, -1.32104985, -0.33485402, -1.17525795]])

(array([[ 0.13135408,  0.45464187, -0.44448955,  0.2344228 , -0.49713174],
        [-0.03671481, -0.20233003,  0.05194735, -0.91432808,  0.27352979],
        [ 0.10145623, -0.29180839, -0.45014431, -0.43606147, -0.75474979],
        [ 0.2261036 , -0.35401562,  0.28184454, -0.81817938,  0.16052105],
        [ 0.83920887,  0.74303828, -0.32104985, -0.33485402, -0.17525795]]),
 array([[ 0.,  1., -0.,  0., -0.],
        [-0., -1.,  0., -1.,  0.],
        [ 1., -2., -0., -0., -0.],
        [ 0., -0.,  0., -1.,  0.],
        [ 0.,  0., -1., -0., -1.]]))

## 1.6 ```np.isnan```和```np.isfinite\np.isinf```函数

In [21]:
# np.isnan函数判断数组中值是否为NaN
a = np.random.randn(3,5)
a[1,1] = np.nan
np.isnan(a)

array([[False, False, False, False, False],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [26]:
# np.isfinite函数判断数组中值是否为有限的（非无限或NaN）
a = np.random.randn(3,5)
a[1,1] = np.nan
np.isfinite(a)

array([[ 0.01763078,  0.02206546,  0.57504753,  0.19743855, -1.08848307],
       [-0.61869512,         nan,  0.33333333,  1.54992949,  1.82879915],
       [-1.70022779,  0.42412349, -1.47988864,  1.4839917 , -1.04093844]])

array([[ True,  True,  True,  True,  True],
       [ True, False,  True,  True,  True],
       [ True,  True,  True,  True,  True]])

In [36]:
# np.isinf函数判断数组中值是否为无限大，同时可以指定out参数以就地将返回结果赋值
y=np.array([1,1,1])
np.isinf(np.array([np.inf,-np.inf,np.nan]),y)
y

array([1, 1, 0])

array([1, 1, 0])

## 1.7 一系列三角函数
> sin,cos,tan

> sinh,cosh,tanh

>arcsin,arccos,arctan

>arcsinh,arccosh,arctanh

## 1.8 ```np.logical_not\np.logical_and\np.logical_or\np.logical_xor```函数

In [48]:
# XOR为异或运算，表示两个值相同时返回0，两个值不同时返回1
a = np.arange(5)
np.logical_and(a>2, a<4)
np.logical_not(a<3)
np.logical_or(a>3, a<1)
np.logical_xor(a>3, a<1)

array([False, False, False,  True, False])

array([False, False, False,  True,  True])

array([ True, False, False, False,  True])

array([ True, False, False, False,  True])

# 2 二元通用函数

## 2.1 ```np.add\np.subtract\np.multiply\np.divide\np.floor_divide```加减乘除及整除运算

In [62]:
a = np.zeros((5,5))
b = np.random.randn(5,5)
np.add(a,b)
np.subtract(a,b)
np.multiply(a,b)

array([[-2.39053062,  0.57485001,  1.60466814,  0.61354767,  0.64951638],
       [ 1.60944492, -1.06316097, -0.09033382, -0.10636948, -0.32311009],
       [-0.29903563,  0.14937535,  1.07314615,  1.41320316, -2.5653495 ],
       [ 0.43889615, -0.62432436,  0.97183208, -0.46231636,  0.60630222],
       [-1.52300961, -0.78784933,  0.83791322,  0.68592725, -0.95047968]])

array([[ 2.39053062, -0.57485001, -1.60466814, -0.61354767, -0.64951638],
       [-1.60944492,  1.06316097,  0.09033382,  0.10636948,  0.32311009],
       [ 0.29903563, -0.14937535, -1.07314615, -1.41320316,  2.5653495 ],
       [-0.43889615,  0.62432436, -0.97183208,  0.46231636, -0.60630222],
       [ 1.52300961,  0.78784933, -0.83791322, -0.68592725,  0.95047968]])

array([[-0.,  0.,  0.,  0.,  0.],
       [ 0., -0., -0., -0., -0.],
       [-0.,  0.,  0.,  0., -0.],
       [ 0., -0.,  0., -0.,  0.],
       [-0., -0.,  0.,  0., -0.]])

In [81]:
# np.floor_divide运算返回除法运算的整数部分
a = np.array([1,2,3,4])
b = np.array([2,2,2,2])
np.divide(a,b)
np.floor_divide(a,b)

array([0.5, 1. , 1.5, 2. ])

array([0, 1, 1, 2], dtype=int32)

## 2.2 ```np.power```乘方运算

In [83]:
a = np.arange(9).reshape(3,3)
np.power(a,[1,2,3])

array([[  0,   1,   8],
       [  3,  16, 125],
       [  6,  49, 512]], dtype=int32)

## 2.3 ```np.maximum\np.fmax```函数(```np.minimun\np.fmin```同理)

In [87]:
# np.maximum函数返回数组中的最大值
a = np.arange(9).reshape(3,3)
b = a+1
np.maximum(a,b)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [93]:
# np.fmax返回数组中的最大值并且忽略NaN
a = np.array([[0,1,2],[np.nan,4,5],[6,7,8]])
a
b = np.arange(1,10).reshape(3,3)
# np.maximum(a,b)
np.fmax(a,b)

array([[ 0.,  1.,  2.],
       [nan,  4.,  5.],
       [ 6.,  7.,  8.]])

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

## 2.4 ```np.mod```求余函数

In [94]:
np.mod([1,2,3],2)

array([1, 0, 1], dtype=int32)

## 2.5 ```np.copysign```复制正负函数

In [97]:
np.copysign([1,2,3],-2)
np.copysign([1,2,3],[1,-2,-3])

array([-1., -2., -3.])

array([ 1., -2., -3.])

## 2.6 一系列比较运算符 $>,\ge,<,\le,==,!=$

In [ ]:
# 大于
np.greater
# 大于等于
np.greater_equal
# 小于
np.less
# 小于等于
np.less_equal
# 等于
np.equal
# 不等于
np.not_equal